sudo: required
services:
    - docker
before_install:
  - docker build -t quaqmre/docker-react -f Dockerfile.dev .

script:
    - docker run quaqmre/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$aws_ac_key"
  secret_access_key:
    secure: "$aws_sec_key"
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-258614982808"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws_ac_key
  secret_access_key:
    secure: "$aws_sec_key"

